# Generated by Django 4.2.2 on 2023-06-24 06:19

import django.core.validators
from django.db import migrations, models
import fruitipedia_app.validators.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(30), fruitipedia_app.validators.validators.validate_name_only_letters], verbose_name='Name')),
                ('image', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('nutrition', models.TextField(verbose_name='Nutrition')),
            ],
        ),
    ]
