# Generated by Django 4.2.2 on 2023-06-24 07:41

import django.core.validators
from django.db import migrations, models
import fruitipedia_app.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitmodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), fruitipedia_app.validators.validators.validate_name_only_letters], verbose_name='Name'),
        ),
    ]
